# 默认的profile为dev,其他环境通过制定启动参数使用不同的profile,比如:
#   测试环境: java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境: java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev

#---
#spring:
#  profiles: prod
notfound:
  heading: 您所访问的资源不存在
  summary: 服务器找不到您所请求的资源。
  suggestions:
  - 请检查 URL 以确保路径正确
internal:
  heading: 服务器内部错误
  summary: 服务器遇到了一个未曾预料的状况，导致无法完成对请求的处理。
  suggestions:
  - 一般而言，该问题在服务器程序执行错误时出现
  - 如果问题依然存在，请与服务器管理员联系
others:
  heading: 出错了
  summary: 目前无法提供更多的错误信息！
  suggestions:
  - 如果问题依然存在，请与服务器管理员联系

#---
#spring: 
#  profiles: dev
  
#---
#spring: 
#  profiles: test



  
